use crate::architecture_contract;
use serde_json::{json, Value};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

pub const ADAPTERS: &[&str] = &["dependency-cruiser", "eslint", "nx"];

struct RenderedAdapter {
    path: &'static str,
    content: String,
    mapped_rules: BTreeSet<String>,
    unsupported_rules: BTreeSet<String>,
    requirements: Vec<String>,
    limitations: Vec<String>,
    applicable: bool,
}

fn contract_for(root: &Path) -> Result<Value, String> {
    match architecture_contract::load_contract(root)? {
        Some(contract) => Ok(contract),
        None => architecture_contract::contract(root, &[]),
    }
}

fn rule_ids(contract: &Value) -> BTreeSet<String> {
    contract["rules"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(|rule| rule["id"].as_str())
        .map(str::to_string)
        .collect()
}

fn has(rules: &BTreeSet<String>, id: &str) -> bool {
    rules.contains(id)
}

fn dependency_cruiser(contract: &Value) -> RenderedAdapter {
    let rules = rule_ids(contract);
    let mut forbidden = Vec::new();
    let mut mapped = BTreeSet::new();

    if has(&rules, "dependency.no-import-cycles") {
        forbidden.push(json!({
            "name": "ah-no-import-cycles",
            "comment": "Agentic Harness rule dependency.no-import-cycles",
            "severity": "error",
            "from": {},
            "to": {"circular": true}
        }));
        mapped.insert("dependency.no-import-cycles".to_string());
    }

    if has(&rules, "nuxt.boundary.app-server") {
        for (suffix, from, to) in [
            ("app-to-server", "^app/", "^server/"),
            ("server-to-app", "^server/", "^app/"),
        ] {
            forbidden.push(json!({
                "name": format!("ah-nuxt-{suffix}"),
                "comment": "Agentic Harness rule nuxt.boundary.app-server",
                "severity": "error",
                "from": {"path": from},
                "to": {"path": to}
            }));
        }
        mapped.insert("nuxt.boundary.app-server".to_string());
    }

    if has(&rules, "nuxt.shared.neutral-boundary") {
        forbidden.push(json!({
            "name": "ah-nuxt-shared-neutral",
            "comment": "Agentic Harness rule nuxt.shared.neutral-boundary",
            "severity": "error",
            "from": {"path": "^shared/"},
            "to": {"path": "^(app|server)/"}
        }));
        mapped.insert("nuxt.shared.neutral-boundary".to_string());
    }

    let layered = [
        ("layered.presentation-direction", "^(src/)?presentation/", "^(src/)?infrastructure/"),
        ("layered.application-direction", "^(src/)?application/", "^(src/)?(presentation|infrastructure)/"),
        ("layered.domain-independent", "^(src/)?domain/", "^(src/)?(presentation|application|infrastructure)/"),
        ("layered.infrastructure-inward", "^(src/)?infrastructure/", "^(src/)?(presentation|application)/"),
    ];
    for (id, from, to) in layered {
        if has(&rules, id) {
            forbidden.push(json!({
                "name": format!("ah-{}", id.replace('.', "-")),
                "comment": format!("Agentic Harness rule {id}"),
                "severity": "error",
                "from": {"path": from},
                "to": {"path": to}
            }));
            mapped.insert(id.to_string());
        }
    }

    let unsupported = rules
        .difference(&mapped)
        .filter(|id| {
            id.as_str() == "feature-first.no-cross-feature-internals"
                || id.as_str() == "feature-first.shared-not-dumping-ground"
        })
        .cloned()
        .collect::<BTreeSet<_>>();

    let forbidden_text = serde_json::to_string_pretty(&forbidden).unwrap();
    let content = format!(
        "// Generated by Agentic Harness. Regenerate from .agentic/architecture.json.\n// Canonical rule IDs are preserved in each rule comment.\nmodule.exports = {{\n  forbidden: {forbidden_text}\n}};\n"
    );

    RenderedAdapter {
        path: ".agentic/generated/architecture/dependency-cruiser.cjs",
        content,
        mapped_rules: mapped,
        unsupported_rules: unsupported,
        requirements: vec!["dependency-cruiser".to_string()],
        limitations: vec![
            "Feature-owner capture rules are not approximated because plain dependency-cruiser path rules cannot safely compare arbitrary feature names.".to_string(),
        ],
        applicable: true,
    }
}

fn push_element(elements: &mut Vec<Value>, typ: &str, pattern: &str) {
    elements.push(json!({"type": typ, "pattern": pattern}));
}

fn eslint(contract: &Value) -> RenderedAdapter {
    let rules = rule_ids(contract);
    let mut elements = Vec::new();
    let mut policies = Vec::new();
    let mut mapped = BTreeSet::new();

    let has_layered = [
        "layered.presentation-direction",
        "layered.application-direction",
        "layered.domain-independent",
        "layered.infrastructure-inward",
    ]
    .iter()
    .any(|id| has(&rules, id));

    if has_layered {
        for layer in ["presentation", "application", "domain", "infrastructure"] {
            push_element(&mut elements, &format!("ah-{layer}"), &format!("src/{layer}/**"));
            push_element(&mut elements, &format!("ah-{layer}"), &format!("{layer}/**"));
        }
    }

    let layered = [
        ("layered.presentation-direction", "ah-presentation", vec!["ah-infrastructure"]),
        ("layered.application-direction", "ah-application", vec!["ah-presentation", "ah-infrastructure"]),
        ("layered.domain-independent", "ah-domain", vec!["ah-presentation", "ah-application", "ah-infrastructure"]),
        ("layered.infrastructure-inward", "ah-infrastructure", vec!["ah-presentation", "ah-application"]),
    ];
    for (id, from, disallowed) in layered {
        if has(&rules, id) {
            policies.push(json!({
                "from": {"element": {"type": from}},
                "disallow": {"to": {"element": {"types": {"anyOf": disallowed}}}},
                "message": format!("Agentic Harness rule {id}")
            }));
            mapped.insert(id.to_string());
        }
    }

    if has(&rules, "nuxt.boundary.app-server") || has(&rules, "nuxt.shared.neutral-boundary") {
        for (typ, pattern) in [
            ("ah-nuxt-app", "app/**"),
            ("ah-nuxt-server", "server/**"),
            ("ah-nuxt-shared", "shared/**"),
        ] {
            push_element(&mut elements, typ, pattern);
        }
    }

    if has(&rules, "nuxt.boundary.app-server") {
        policies.push(json!({
            "from": {"element": {"type": "ah-nuxt-app"}},
            "disallow": {"to": {"element": {"type": "ah-nuxt-server"}}},
            "message": "Agentic Harness rule nuxt.boundary.app-server"
        }));
        policies.push(json!({
            "from": {"element": {"type": "ah-nuxt-server"}},
            "disallow": {"to": {"element": {"type": "ah-nuxt-app"}}},
            "message": "Agentic Harness rule nuxt.boundary.app-server"
        }));
        mapped.insert("nuxt.boundary.app-server".to_string());
    }

    if has(&rules, "nuxt.shared.neutral-boundary") {
        policies.push(json!({
            "from": {"element": {"type": "ah-nuxt-shared"}},
            "disallow": {"to": {"element": {"types": {"anyOf": ["ah-nuxt-app", "ah-nuxt-server"]}}}},
            "message": "Agentic Harness rule nuxt.shared.neutral-boundary"
        }));
        mapped.insert("nuxt.shared.neutral-boundary".to_string());
    }

    let unsupported = rules
        .difference(&mapped)
        .filter(|id| {
            id.as_str() == "dependency.no-import-cycles"
                || id.as_str() == "feature-first.no-cross-feature-internals"
                || id.as_str() == "feature-first.shared-not-dumping-ground"
        })
        .cloned()
        .collect::<BTreeSet<_>>();

    let elements_text = serde_json::to_string_pretty(&elements).unwrap();
    let policies_text = serde_json::to_string_pretty(&policies).unwrap();
    let content = format!(
        "// Generated by Agentic Harness. Import this flat-config fragment from your eslint.config.mjs.\n// Requires eslint-plugin-boundaries.\nimport boundaries from \"eslint-plugin-boundaries\";\n\nexport default [{{\n  name: \"agentic-harness/architecture\",\n  plugins: {{ boundaries }},\n  settings: {{\n    \"boundaries/elements\": {elements_text}\n  }},\n  rules: {{\n    \"boundaries/dependencies\": [2, {{\n      default: \"allow\",\n      policies: {policies_text}\n    }}]\n  }}\n}}];\n"
    );

    RenderedAdapter {
        path: ".agentic/generated/architecture/eslint-boundaries.mjs",
        content,
        mapped_rules: mapped,
        unsupported_rules: unsupported,
        requirements: vec!["eslint".to_string(), "eslint-plugin-boundaries".to_string()],
        limitations: vec![
            "Import-cycle enforcement is intentionally left to the native Harness analyzer or a dedicated ESLint cycle plugin rather than silently adding another dependency.".to_string(),
            "Feature-to-feature owner comparison is not emitted until the adapter can preserve feature-name captures without broad false positives.".to_string(),
        ],
        applicable: true,
    }
}

fn nx(contract: &Value, root: &Path) -> RenderedAdapter {
    let rules = rule_ids(contract);
    let applicable = root.join("nx.json").is_file();
    let mut constraints = Vec::new();
    let mut assignments = Vec::new();
    let mut mapped = BTreeSet::new();

    let layered = [
        ("layered.presentation-direction", "layer:presentation", vec!["layer:infrastructure"]),
        ("layered.application-direction", "layer:application", vec!["layer:presentation", "layer:infrastructure"]),
        ("layered.domain-independent", "layer:domain", vec!["layer:presentation", "layer:application", "layer:infrastructure"]),
        ("layered.infrastructure-inward", "layer:infrastructure", vec!["layer:presentation", "layer:application"]),
    ];
    for (id, source_tag, disallowed) in layered {
        if has(&rules, id) {
            constraints.push(json!({
                "sourceTag": source_tag,
                "notDependOnLibsWithTags": disallowed,
                "source_rule_id": id
            }));
            mapped.insert(id.to_string());
        }
    }
    if mapped.iter().any(|id| id.starts_with("layered.")) {
        for layer in ["presentation", "application", "domain", "infrastructure"] {
            assignments.push(json!({
                "paths": [format!("src/{layer}/**"), format!("{layer}/**")],
                "suggested_project_tag": format!("layer:{layer}")
            }));
        }
    }

    if has(&rules, "nuxt.boundary.app-server") {
        constraints.push(json!({
            "sourceTag": "runtime:app",
            "notDependOnLibsWithTags": ["runtime:server"],
            "source_rule_id": "nuxt.boundary.app-server"
        }));
        constraints.push(json!({
            "sourceTag": "runtime:server",
            "notDependOnLibsWithTags": ["runtime:app"],
            "source_rule_id": "nuxt.boundary.app-server"
        }));
        mapped.insert("nuxt.boundary.app-server".to_string());
        assignments.push(json!({"paths":["app/**"],"suggested_project_tag":"runtime:app"}));
        assignments.push(json!({"paths":["server/**"],"suggested_project_tag":"runtime:server"}));
    }
    if has(&rules, "nuxt.shared.neutral-boundary") {
        constraints.push(json!({
            "sourceTag": "runtime:shared",
            "notDependOnLibsWithTags": ["runtime:app", "runtime:server"],
            "source_rule_id": "nuxt.shared.neutral-boundary"
        }));
        mapped.insert("nuxt.shared.neutral-boundary".to_string());
        assignments.push(json!({"paths":["shared/**"],"suggested_project_tag":"runtime:shared"}));
    }

    let unsupported = rules
        .difference(&mapped)
        .filter(|id| {
            id.as_str() == "dependency.no-import-cycles"
                || id.as_str() == "feature-first.no-cross-feature-internals"
                || id.as_str() == "feature-first.shared-not-dumping-ground"
        })
        .cloned()
        .collect::<BTreeSet<_>>();

    let artifact = json!({
        "format_version": 1,
        "kind": "agentic-harness-nx-boundary-fragment",
        "applicable": applicable,
        "rule": "@nx/enforce-module-boundaries",
        "depConstraints": constraints,
        "tag_assignments": assignments,
        "notes": [
            "Merge depConstraints into @nx/enforce-module-boundaries.",
            "Tags are project-level in Nx; suggested path mappings require matching Nx project boundaries before they can enforce intra-repository architecture."
        ]
    });
    let mut content = serde_json::to_string_pretty(&artifact).unwrap();
    content.push('\n');

    RenderedAdapter {
        path: ".agentic/generated/architecture/nx-boundaries.json",
        content,
        mapped_rules: mapped,
        unsupported_rules: unsupported,
        requirements: vec!["Nx workspace".to_string(), "@nx/eslint-plugin or compatible Nx boundary runner".to_string()],
        limitations: vec![
            "Nx constraints operate between tagged projects; folder-only layers inside one Nx project remain enforced by the native Harness analyzer instead.".to_string(),
        ],
        applicable,
    }
}

fn render(root: &Path, adapter: &str, contract: &Value) -> Result<RenderedAdapter, String> {
    match adapter {
        "dependency-cruiser" => Ok(dependency_cruiser(contract)),
        "eslint" => Ok(eslint(contract)),
        "nx" => Ok(nx(contract, root)),
        _ => Err(format!(
            "unknown architecture adapter: {adapter}; expected {}",
            ADAPTERS.join("|")
        )),
    }
}

pub fn generate(root: &Path, adapter: &str, write: bool) -> Result<Value, String> {
    let contract = contract_for(root)?;
    let rendered = render(root, adapter, &contract)?;
    let destination = root.join(rendered.path);
    if write {
        if !rendered.applicable {
            return Err(format!(
                "adapter `{adapter}` is not applicable to this project; refusing to write {}",
                rendered.path
            ));
        }
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {}: {error}", parent.display()))?;
        }
        fs::write(&destination, &rendered.content)
            .map_err(|error| format!("failed to write {}: {error}", destination.display()))?;
    }

    Ok(json!({
        "format_version": 1,
        "kind": "architecture-adapter",
        "adapter": adapter,
        "applicable": rendered.applicable,
        "write": write,
        "path": rendered.path,
        "mapped_rules": rendered.mapped_rules,
        "unsupported_rules": rendered.unsupported_rules,
        "requirements": rendered.requirements,
        "limitations": rendered.limitations,
        "content": rendered.content,
        "source_contract": architecture_contract::CONTRACT_PATH,
        "registry_schema_version": contract["registry_schema_version"]
    }))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;
    use std::path::PathBuf;

    fn fixture(name: &str) -> PathBuf {
        let path = env::temp_dir().join(format!("ah-architecture-adapter-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).unwrap();
        path
    }

    fn write_contract(root: &Path, profiles: &[&str]) {
        let requested = profiles.iter().map(|value| (*value).to_string()).collect::<Vec<_>>();
        architecture_contract::write(root, &requested).unwrap();
    }

    #[test]
    fn dependency_cruiser_maps_cycles_and_layered_rules() {
        let root = fixture("dependency-cruiser");
        write_contract(&root, &["pattern/layered/1"]);
        let result = generate(&root, "dependency-cruiser", false).unwrap();
        assert!(result["content"].as_str().unwrap().contains("circular"));
        assert!(result["mapped_rules"].as_array().unwrap().iter().any(|id| id == "layered.domain-independent"));
        assert!(!root.join(result["path"].as_str().unwrap()).exists());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn eslint_maps_layered_boundaries_without_approximating_cycles() {
        let root = fixture("eslint");
        write_contract(&root, &["pattern/layered/1"]);
        let result = generate(&root, "eslint", false).unwrap();
        let content = result["content"].as_str().unwrap();
        assert!(content.contains("boundaries/dependencies"));
        assert!(result["unsupported_rules"].as_array().unwrap().iter().any(|id| id == "dependency.no-import-cycles"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn nx_emits_tag_constraints_only_as_applicable_for_nx_workspace() {
        let root = fixture("nx");
        write_contract(&root, &["pattern/layered/1"]);
        let preview = generate(&root, "nx", false).unwrap();
        assert_eq!(preview["applicable"], false);
        assert!(generate(&root, "nx", true).is_err());
        fs::write(root.join("nx.json"), "{}").unwrap();
        let applicable = generate(&root, "nx", false).unwrap();
        assert_eq!(applicable["applicable"], true);
        assert!(applicable["content"].as_str().unwrap().contains("notDependOnLibsWithTags"));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn write_is_stable_and_regenerates_same_content() {
        let root = fixture("stable");
        write_contract(&root, &["framework/nuxt/4"]);
        let first = generate(&root, "dependency-cruiser", true).unwrap();
        let first_content = fs::read_to_string(root.join(first["path"].as_str().unwrap())).unwrap();
        let second = generate(&root, "dependency-cruiser", true).unwrap();
        let second_content = fs::read_to_string(root.join(second["path"].as_str().unwrap())).unwrap();
        assert_eq!(first_content, second_content);
        let _ = fs::remove_dir_all(root);
    }
}
